import Head from "next/head";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Image from "@/components/Image";
import Info from "@/components/Info";
import Visit from "@/components/Visit";
import Impact from "@/components/Impact";
import UkraineCard from "@/components/UkraineCard";
import ImgCard from "@/components/ImgCard";
import ImageCards from "@/components/imageCards";
import { BsArrowRight } from "react-icons/bs";
import Calendar from "@/components/Calendar";
import Features from "@/components/Features";
import InfiniteScroll from "@/components/InfiniteScroll";
import Tour from "@/components/Tour";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray text-[#333333] relative">
        <div className="flex">
          <Navbar />
        </div>
        <div className="bg-white max-w-[1600px] mx-auto shadow-xl overflow-hidden">
          <Hero />
        </div>
        <Image />
        <div className="bg-white max-w-[1600px] mx-auto shadow-xl overflow-hidden">
          <Info />
          <Visit />
          <Impact />
          {/* <UkraineCorona /> */}
          <div className="grid grid-cols-2 gap-8 py-24 max-w-[1250px] mx-auto">
            <UkraineCard />
            <UkraineCard />
          </div>
          {/* ImageCards component */}
          <div className="bg-gray py-24">
            <p className="text-darkBlue text-3xl font-semibold max-w-[1250px] mx-auto mb-12">
              NEWS
            </p>
            <div
              className="grid grid-cols-2 max-w-[1250px] mx-auto
    "
            >
              <div className="grid gap-6">
                <ImgCard />
                <ImgCard />
              </div>
              <div className="gap-24 grid justify-self-end">
                {" "}
                <ImgCard
                  styles={"max-w-[150px] w-[150px] max-h-[114px] h-[114px]"}
                />
                <ImgCard
                  styles={"max-w-[150px] w-[150px] max-h-[114px] h-[114px]"}
                />
                <ImgCard
                  styles={"max-w-[150px] w-[150px] max-h-[114px] h-[114px]"}
                />
              </div>
            </div>{" "}
            <div
              className="font-semibold max-w-[1250px] mx-auto text-lg flex w-full justify-center mt-28
            "
            >
              <p className="flex gap-6 items-center">
                {" "}
                News Overview
                <BsArrowRight />
              </p>
            </div>
          </div>
          <Calendar />
          <div className="bg-gray">
            <Visit />
          </div>
          <InfiniteScroll />
          <Tour />
          <Features />
          <Footer />
        </div>
      </div>
    </>
  );
}
